Bruh1/Areas/BillOperations/Controllers/BillController.cs
using ViewModels.Bills;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using MVC.Areas.ItemOperations.Controllers;
using MVC.Attributes;
using MVC.Controllers;
using ProviderLayer.Processors;

namespace MVC.Areas.BillOperations.Controllers
{
    [OOAuthorizeAttribute]
    [Area("BillOperations")]
    public class BillController : BaseController
    {
        private readonly ILogger<ItemController> _logger;

        public BillController(IConfiguration config, ILogger<ItemController> logger)
        {
            _configuration = config;
        }
        
        public async Task<IActionResult> Index()
        {
            using BillProcessor billProcessor = new BillProcessor(_configuration);
            var result = await billProcessor.GetAll();

            int[] idArray = result.ReturnData as int[];

            int maxID = idArray[0];
            int maxDetailID = idArray[1];

            maxID++;
            maxDetailID++;

            ViewBag.maxID = maxID;
            ViewBag.maxDetailID = maxDetailID;

            return View(result.Item1);
        }

        public IActionResult HeaderSlice(BillHeader model)
        {
            return PartialView(model);
        }

        public IActionResult DetailSlice(BillDetail model)
        {
            return PartialView(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

Bruh1/Areas/ClientOperations/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Attributes;
using MVC.Controllers;
using ProviderLayer.Processors;
using ViewModels;

namespace MVC.Areas.ClientOperations.Controllers
{
    [Area("ClientOperations")]
    [OOAuthorize]
    public class ClientController : BaseController
    {
        private readonly ILogger<ClientController> _logger;

        public ClientController(ILogger<ClientController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index() 
        {
            using ClientProcessor clientProvider = new ClientProcessor(_configuration);
            var queryReturn = await clientProvider.GetAll();
            var clientModels = queryReturn.Item1;
            int maxID = (int)queryReturn.ReturnData;
            maxID++;
            ViewBag.maxID = maxID;
            return View(clientModels);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Submission(Client model)
        {
            if (ModelState.IsValid)
            {
                using ClientProcessor clientProvider = new ClientProcessor(_configuration);
                var updateReturn = await clientProvider.Update(model);
                bool isSuccess = updateReturn.success;
                int maxID = (int)updateReturn.ReturnData;

                return createresponse(isSuccess, "Done.");
            }
            return createresponse(false, "Form Invalid");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                using ClientProcessor clientProvider = new ClientProcessor(_configuration);
                bool isSuccess = await clientProvider.Delete(id);
                return createresponse(isSuccess, "Item Deleted");
            }
            else return createresponse(false, "Delete Form Invalid.");
        }

        [HttpPost]
        public IActionResult ClientSlice(Client model)
        {
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

Bruh1/Areas/ItemOperations/Controllers/ItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC.Attributes;
using MVC.Controllers;
using ProviderLayer.Processors;
using System.Reflection;
using System.Runtime.CompilerServices;
using ViewModels;

namespace MVC.Areas.ItemOperations.Controllers
{
    [Area("ItemOperations")]
    [OOAuthorizeAttribute]
    public class ItemController : BaseController
    {
        private readonly ILogger<ItemController> _logger;

        public ItemController(ILogger<ItemController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;

        }
         
        public async Task<IActionResult> Index()
        {
             using  ItemProcessor itemProvider = new ItemProcessor(_configuration);
            var queryResult = await itemProvider.GetAll();
            var Models = queryResult.Item1;
            var maxID = (int)queryResult.ReturnData;
            maxID++; 
            ViewBag.maxID = maxID;
            return View(Models);
        }

        [HttpPost] 
        [ValidateAntiForgeryToken]
            public async Task<IActionResult> Submission(Item model)
            {
                if (ModelState.IsValid)
                {
                     using  ItemProcessor itemProvider = new ItemProcessor(_configuration);
                    var update = await itemProvider.Update(model);
                    var maxID = update.ReturnData;
                

                    return createresponse(update.success, "Good", new {maxID, model});
                }

                return createresponse(false,"Something went wrong");
            }

        [HttpPost] 
        public IActionResult ItemSlice(Item model)
        {
            return PartialView(model);
        }
         
        public async Task<IActionResult> CreateBar()
        {
             using  ItemProcessor itemProvider = new ItemProcessor(_configuration);
            var queryResult = await itemProvider.GetAll();
            int maxID = (int)queryResult.ReturnData;
            maxID++;
            ViewBag.maxID = maxID;
            return PartialView();
        }

        [HttpPost] 
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                 using  ItemProcessor itemProvider = new ItemProcessor(_configuration);
                bool isSucess = await itemProvider.Delete(id);
                return createresponse(isSucess, "Item Deleted Successfully.");
            }
            return createresponse(false, "Data Validation Failed.");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }


    }
}

Bruh1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu|Quicksand">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>

<body class="light ltr">
        @if (User.Identity.IsAuthenticated)
        {
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3 navbar-sticky">
                    <div class="container-fluid">
                        <a class="navbar-brand link link-dark" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link link link-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link link link-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link link link-dark" asp-area="ClientOperations" asp-controller="Client" asp-action="Index">Clients</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link link link-dark" asp-area="ItemOperations" asp-controller="Item" asp-action="Index">Items</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link link link-dark float-end" asp-area="BillOperations" asp-controller="Bill" asp-action="Index">Bills</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        }
    <div class="fill" >
        <main role="main" class="fill">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted align-bottom">
        <div class="container">
            &copy; 2024 - MVC - <a class="link link-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/Helpers/AjaxHelpers.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>